
# Makefile for UTM pkl'er

# TL;DR: essentially builds the .pkl files /Manifests into UTM virtual machines in /Machines
#        each .pkl becomes a .utm directory, and will "open" in UTM App directly after build
#        a .zip file can be used with utm://downloadVM?url= to install a VM into UTM

# NOTE: No "partial" build - so a build will overwrite disks!
#   Thus, while VMs will run from the /Machines directory, any changes will be lost on next `make`. 

.PHONY: all prereq phase1 phase2 pkl clean 
.SUFFIXES: 

# basic build "from" and "to" here...
PKL_RUN_DIR := Manifests
PKL_OUTPUT_DIR := Machines
PKL_FILES_DIR := Files

# machine specific properties
CHR_VERSION ?= stable

# options for `pkl` build
# PKL_OPTIONS := -e chrVersion=$(CHR_VERSION)


all: prereq phase1 
	$(info all done)

prereq:
	pkl --version
	make --version
	qemu-img --version
	$(info prereq completed)
	
clean:
	$(info cleaning $(PKL_OUTPUT_DIR))
	rm -rf ./$(PKL_OUTPUT_DIR)

# pkl creates the initial files /Manifasts to kickstart a UTM ZIP
phase1: pkl
	$(info ran build phase1)
	$(info recursively call make build now placeholder files are created)
	$(MAKE) phase2
pkl:
	$(info running pkl)
	pkl eval ./$(PKL_RUN_DIR)/*.pkl $(PKL_OPTIONS) -m ./$(PKL_OUTPUT_DIR)

# NOTES:  This Makefile is recursive. `pkl` is run first which produces
#	      some placeholder files like .url, then `make` is run again
#         to find those placeholders in PKL_OUTPUT_DIR ("/Machines").
#		  The found files become targets and deps, with make pattern rules
#         doing the heavy lifting to download, unzip, or run commands.

# pattern rules run the show
%.raw: %.raw.url
	wget -O $@ `cat $<`
%.img: %.img.zip.url
	wget -O $@.zip `cat $<`
	unzip -o $(subst .url,,$<) -d $(dir $@)
	rm $(subst .url,,$<)
%.qcow2: %.qcow2.zip.url
	wget -O $@.zip `cat $<`
	unzip -o $(subst .url,,$<) -d $(dir $@)
	rm $(subst .url,,$<)
%.qcow2: %.size
	qemu-img create -f qcow2 $@ `cat $<`M
%: %.localcp
	cp -f ./$(PKL_FILES_DIR)/`cat $<` $@

# search for placeholder files
#   note: these will only work AFTER `pkl`, and why Makefile is recursive
URLFILES := $(wildcard ./$(PKL_OUTPUT_DIR)/*/Data/*.raw.url)
URLTARGETS := $(URLFILES:.url=)
ZIPIMGFILES := $(wildcard ./$(PKL_OUTPUT_DIR)/*/Data/*img.zip.url)
ZIPIMGTARGETS := $(ZIPIMGFILES:.zip.url=)
SIZEFILE := $(wildcard ./$(PKL_OUTPUT_DIR)/*/Data/*.size)
SIZETARGETS := $(subst .size,.qcow2,$(SIZEFILE))
LOCALCPFILE := $(wildcard ./$(PKL_OUTPUT_DIR)/*/Data/*.localcp)
LOCALCPTARGETS := $(subst .localcp,,$(LOCALCPFILE))

# links all targets together from found placeholders
phase2: libvirt-fixpaths qemu-chmod $(LOCALCPTARGETS) $(SIZETARGETS) $(URLTARGETS) $(ZIPIMGTARGETS)
	$(info ran build phase2)
	$(info used deps: $?)

# download OS drive images
$(URLTARGETS): $(URLFILES)

# images may need unzip & handled seperately here
$(ZIPIMGTARGETS): $(ZIPIMGFILES)

# creates QEMU spare/empty disks
$(SIZETARGETS): $(SIZEFILE)

# converts a .localcp file into a file copy from /Files
$(LOCALCPTARGETS): $(LOCALCPFILE)

# unused currently, for debugging Makefile
.PHONY: debug-patterns
debug-patterns:
	$(info debug URLFILES $(URLFILES))
	$(info debug URLTARGETS $(URLTARGETS))
	$(info debug SIZEFILE $(SIZEFILE))
	$(info debug SIZETARGETS $(SIZETARGETS))
	$(info debug ZIPIMGFILES $(ZIPIMGFILES))
	$(info debug ZIPIMGTARGETS $(ZIPIMGTARGETS))

# macOS-only helpers for UTM
.PHONY: utm-version utm-install utm-uninstall utm-stop utm-start 

tellvm = osascript -e 'tell application "UTM" to $(2) virtual machine named "$(1)"'
doallvms = for i in $(subst .utm,,$(notdir $(wildcard ./$(PKL_OUTPUT_DIR)/*.utm))); do osascript -e "tell application \"UTM\" to $(1) virtual machine named \"$$i\"" ; done

utm-version:
	osascript -e 'get version of application "UTM"'

utm-install: $(wildcard ./$(PKL_OUTPUT_DIR)/*.utm)
	for i in $^; do open $$i; done

utm-uninstall:
	$(call doallvms, delete)

utm-stop:
	$(call doallvms, stop)

utm-start:
	$(call doallvms, start)

# libvirt helpers (Linux / CI - requires libvirt/virsh and qemu installed)
# libvirt.xml files are generated by pkl directly into each *.utm bundle.
# The disk paths in libvirt.xml are relative ("./Data/..."), so virsh must be
# run from the *.utm directory, or the paths adjusted for a permanent installation.

LIBVIRT_XMLFILES := $(wildcard ./$(PKL_OUTPUT_DIR)/*.utm/libvirt.xml)

.PHONY: libvirt-list libvirt-fixpaths libvirt-define libvirt-start libvirt-stop libvirt-undefine libvirt-validate libvirt-run-qemu

# Show all libvirt.xml files produced by the build
libvirt-list:
	@for f in $(LIBVIRT_XMLFILES); do echo $$f; done

# Replace /LIBVIRT_DATA_PATH placeholder in libvirt.xml with actual absolute Data directory path.
# Run automatically by phase2 or manually at any time after pkl generates the files.
libvirt-fixpaths:
	@for f in $(LIBVIRT_XMLFILES); do \
	  datadir=$$(cd "$$(dirname $$f)" && pwd)/Data; \
	  perl -i -pe "s|/LIBVIRT_DATA_PATH|$$datadir|g" $$f; \
	  echo "libvirt-fixpaths: $$f -> $$datadir"; \
	done

# Validate generated libvirt XML files (requires virt-xml-validate)
libvirt-validate:
	@for f in $(LIBVIRT_XMLFILES); do \
	  echo "Validating $$f ..."; \
	  virt-xml-validate $$f domain || exit 1; \
	done
	@echo "libvirt-validate passed"

# Define (register) all QEMU machines with libvirt from their libvirt.xml
libvirt-define:
	@for f in $(LIBVIRT_XMLFILES); do \
	  echo "Defining $$f ..."; \
	  virsh define $$f; \
	done

# Start all defined libvirt VMs
libvirt-start:
	@for f in $(LIBVIRT_XMLFILES); do \
	  vmname=$$(xmllint --xpath 'string(/domain/name)' $$f 2>/dev/null); \
	  echo "Starting $$vmname ..."; \
	  virsh start "$$vmname"; \
	done

# Stop all libvirt VMs managed here
libvirt-stop:
	@for f in $(LIBVIRT_XMLFILES); do \
	  vmname=$$(xmllint --xpath 'string(/domain/name)' $$f 2>/dev/null); \
	  echo "Stopping $$vmname ..."; \
	  virsh destroy "$$vmname" 2>/dev/null || true; \
	done

# Undefine (deregister) all libvirt VMs managed here
libvirt-undefine:
	@for f in $(LIBVIRT_XMLFILES); do \
	  vmname=$$(xmllint --xpath 'string(/domain/name)' $$f 2>/dev/null); \
	  echo "Undefining $$vmname ..."; \
	  virsh undefine "$$vmname" 2>/dev/null || true; \
	done

# Run a single libvirt VM directly via qemu-system for testing (with REST API port forwarding).
# LIBVIRT_XML must be set to the libvirt.xml path for the machine to run.
# Host port 9180 is forwarded to the VM's port 80 (RouterOS REST API).
# This is used in CI - virsh start is not used because libvirt user networking
# does not support port forwarding without qemu:commandline extensions.
libvirt-run-qemu:
	@test -n "$(LIBVIRT_XML)" || (echo "Set LIBVIRT_XML=<path to libvirt.xml>" && exit 1)
	$(eval _ARCH := $(shell xmllint --xpath 'string(/domain/os/type/@arch)' $(LIBVIRT_XML) 2>/dev/null))
	$(eval _EMULATOR := $(shell xmllint --xpath 'string(/domain/devices/emulator)' $(LIBVIRT_XML) 2>/dev/null))
	$(eval _MEM := $(shell xmllint --xpath 'string(/domain/memory)' $(LIBVIRT_XML) 2>/dev/null))
	$(eval _DISK := $(shell xmllint --xpath 'string(/domain/devices/disk/source/@file)' $(LIBVIRT_XML) 2>/dev/null))
	$(eval _FMT := $(shell xmllint --xpath 'string(/domain/devices/disk/driver/@type)' $(LIBVIRT_XML) 2>/dev/null))
	$(eval _VCPU := $(shell xmllint --xpath 'string(/domain/vcpu)' $(LIBVIRT_XML) 2>/dev/null))
	@echo "Launching $(_EMULATOR) for arch=$(_ARCH) disk=$(_DISK) mem=$(_MEM)MiB vcpu=$(_VCPU)"
	nohup $(_EMULATOR) \
	  -M $$(xmllint --xpath 'string(/domain/os/type/@machine)' $(LIBVIRT_XML) 2>/dev/null) \
	  -m $(_MEM) \
	  -smp $(_VCPU) \
	  -nographic \
	  -drive file=$(_DISK),format=$(_FMT),if=virtio \
	  -netdev user,id=net0,hostfwd=tcp::9180-:80 \
	  -device virtio-net-pci,netdev=net0 \
	  $(LIBVIRT_QEMU_EXTRA) \
	  &>/tmp/qemu-libvirt-test.log &
	echo $$! > /tmp/qemu-libvirt-test.pid
	@echo "QEMU PID=$$(cat /tmp/qemu-libvirt-test.pid) — log: /tmp/qemu-libvirt-test.log"

# QEMU helpers (direct QEMU via qemu.cfg + qemu.sh — no libvirt required)
# qemu.cfg and qemu.sh are generated by pkl directly into each *.utm bundle.
# qemu.cfg is a QEMU --readconfig ini file; qemu.sh is a launcher that handles
# platform-specific flags (UEFI firmware, KVM/TCG, port forwarding, display).

QEMU_CFGFILES := $(wildcard ./$(PKL_OUTPUT_DIR)/*.utm/qemu.cfg)
QEMU_SHFILES := $(wildcard ./$(PKL_OUTPUT_DIR)/*.utm/qemu.sh)

.PHONY: qemu-list qemu-fixpaths qemu-run qemu-stop

# Show all qemu.cfg files produced by the build
qemu-list:
	@for f in $(QEMU_CFGFILES); do echo $$f; done

# No-op: qemu.cfg now uses relative paths (./Data/...) and qemu.sh resolves them
# by changing to its own directory before launching QEMU.
qemu-fixpaths:
	@echo "qemu-fixpaths: no-op (qemu.cfg uses relative paths)"

# Make all qemu.sh scripts executable
qemu-chmod:
	@for f in $(QEMU_SHFILES); do \
	  chmod +x $$f; \
	  echo "qemu-chmod: $$f"; \
	done

# Run a single QEMU machine via its qemu.sh launch script.
# QEMU_UTM must be set to the .utm directory path (e.g. Machines/chr.x86_64.qemu.7.22.utm).
# Passes QEMU_PORT and any extra env vars through to qemu.sh.
qemu-run: qemu-chmod
	@test -n "$(QEMU_UTM)" || (echo "Set QEMU_UTM=<path to .utm dir> (e.g. Machines/chr.x86_64.qemu.7.22.utm)" && exit 1)
	@test -f "$(QEMU_UTM)/qemu.sh" || (echo "No qemu.sh in $(QEMU_UTM)" && exit 1)
	@sh "$(QEMU_UTM)/qemu.sh" --background --port "$${QEMU_PORT:-9180}"

# Stop a running QEMU instance launched by qemu-run
qemu-stop:
	@test -n "$(QEMU_UTM)" || (echo "Set QEMU_UTM=<path to .utm dir>" && exit 1)
	@VMNAME=$$(basename "$(QEMU_UTM)" .utm); \
	  PID_FILE="/tmp/qemu-$$VMNAME.pid"; \
	  if [ -f "$$PID_FILE" ]; then \
	    kill "$$(cat $$PID_FILE)" 2>/dev/null && echo "Stopped $$VMNAME" || echo "$$VMNAME not running"; \
	    rm -f "$$PID_FILE"; \
	  else \
	    echo "No PID file for $$VMNAME"; \
	  fi